CREATE TABLE Cliente
(
CPF VARCHAR(11),
NOME VARCHAR(100),
ENDERECO1 VARCHAR(100),
ENDERECO2 VARCHAR(100),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR(50),
CEP VARCHAR(50),
IDADE SMALLINT,
LIMITE_CREDITO FLOAT,
VOLUME_COMPRA FLOAT,
PRIMEIRA_COMPRA BIT(1)
);
